name: basketball
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  http: ^1.1.0
  html: ^0.15.4
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  flutter_masonry_view: ^0.0.2
  url_launcher: ^6.2.2
  app_settings: ^5.1.1
  share_plus: ^7.2.1
  image_picker: ^1.0.5
  permission_handler: ^11.0.1
  provider: ^6.1.1
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true
  assets:
    - assets/icons/default/home.svg
    - assets/icons/active/home.svg
    - assets/icons/default/notes.svg
    - assets/icons/active/notes.svg
    - assets/icons/default/news.svg
    - assets/icons/active/news.svg
    - assets/icons/default/settings.svg
    - assets/icons/active/settings.svg
    - assets/logo.svg
    - assets/icons/notes/edit.svg
    - assets/icons/notes/trash.svg
    - assets/icons/settings/photo.png
    - assets/icons/settings/PrivacyPolicy.svg
    - assets/icons/settings/TermsofUse.svg
    - assets/icons/settings/Notification.svg
    - assets/icons/settings/ShareApp.svg
  fonts:
    - family: SrbijaSans
      fonts:
        - asset: fonts/SrbijaSans.otf
